### ISSUE TITLE
Error when trying to access var `beautiful.dir`

### ISSUE THREAD

**Issue by vinivosh** [raven2cz/awesomewm-config#5]
Hi! I've been following your tutorials on the TUX series, trying to get your AwesomeWM config working on my system. I think I did everything as shown in the video, but I'm getting some bizarre errors when starting my session in AwesomeWM.

I always get multiple (4–6) notifications of this same error when starting my session: `Oops, an error happened! ...me/fishlive/widget/mebox/menu/templates/applications.lua 182: attempt to concatenate a nil value (field 'dir')`

Strange thing is that your themes are all applied, the theme changer works, the wallpaper changer works, the custom tiling configurations are also present and work normally. But the only keybindings available are the default ones. And AwesomeWM doesn't read stuff from the `config.lua` file at all — my terminal settings there are ignored and only XTerm is used, for some reason.

Also, two top-bars are spawned, instead of just one, and it seems like three sets of "tag selectors" are spawned on each bar, with invalid tags after the valid ones, which spit out errors when I try switching to them. Really strange behaviour.

I honestly don't know what to do about this 😔

**Comment by raven2cz** [comment]
I have several ways to get it up and running. After all, the project is quite large, so it will be better to "unlock" it gradually.

The mentioned error is secondary, because `mebox` requires configurations and it crashed for you during the initialization of the theme, hence it returns null when obtaining a resource from the theme. That's why the keys and other things are not loaded either, because the theme initialization wasn't complete and you're dealing with an interim state.

First, run Xephyr and launch awesome sessions directly in it. In debug mode in your command line, you'll see many more error messages during the initialization process.

Also, temporarily disable `dashboard_enabled = false` in `config.lua` so that `mebox` and the entire `dashboard` don't initialize, reducing your concerns and helping locate missing scripts/applications.

Check out this link too; it's not complete, and there might be something missing. But verify if at least the basic things are installed:
https://github.com/raven2cz/geek-room/tree/main/arch-install-awesomewm

Final point. The basic settings DO NOT have multi-monitor support. My basic session is such that the laptop monitor switches to an external 4K monitor. So if there are two displays, one turns off and the larger external one is used. On the other hand, if the laptop is disconnected, the one with the lower resolution is used as the primary. This is done by additional scripts.

If you need a multi-monitor setup, there's a `sharedtags` library and `rc.lua-dualmonitors` added at the bottom of the project. However, I haven't made it dynamic yet, and it's possible I haven't even merged it. This might cause additional errors if you have a multi-monitor setup and are using `rc.lua`.

**Comment by raven2cz** [comment]
@vinivosh any progress?

**Comment by vinivosh** [comment]
> @vinivosh any progress?

Hey, thank you so much for the help @raven2cz! Great idea, I'll try checking out what's outputed to the terminal when starting a session in Xephyr.

Unfortunately I haven't had much time to tinker with stuff in my system lately because of work and having to write my thesis. I think this weekend I'll be able to give it all a try again and I'll report back.
